version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-mueblerix
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mueblerix
      MYSQL_USER: mueblerix
      MYSQL_PASSWORD: mueblerix123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
